name: 'Continuos Deployment'

on:
    workflow_run:
      workflows: ['Continuous Integration']
      types:
        - completed

jobs:
  # ...
  build:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Api Deployment
        id: 'deploy'
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: 'latam-airlines-challange'
          deliverables: 'app.yaml'