name: 'Continuos Deployment'

on:
    workflow_dispatch:
    push:
      branches:
        - "main"

jobs:
  # ...
  build:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Authentication'
        id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Api Deployment
        id: 'deploy'
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: 'latam-airlines-challange'
          deliverables: 'app.yaml'