name: 'Continuos Deployment'

on:
  workflow_run:
    workflows: ['Continuos Integration']
    types:
      - completed

jobs:
  # ...
  build:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/615507349246/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-actions@latam-airlines-challange.iam.gserviceaccount.com'

      - name: Set Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - id: 'deploy'
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: "615507349246"
          deliverables: 'app.yaml' --quiet