name: 'Continuos Integration'

on:
    workflow_dispatch:
    push:
      branches:
        - "main"
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Chekout code
          uses: actions/checkout@v2
        - name: Python use
          uses: actions/setup-python@v2
          with: 
            python-version: "3.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install -r requirements-test.txt
        - name: Model tests
          run: make model-test
        - name: API tests
          run: make api-test
    